apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  ports:
  - port: {{ .Values.mysql.service.port }}
  selector:
    app: {{ .Values.mysql.service.selector }}
  clusterIP: None
